name = GVJ Page
description = Provides a content type suitable for static content, such as an About Us page
machine_name = gvj_page
version = 7.x-1.0-alpha1
downloadable = gvj_page 7.x-1.0-alpha1
author = Guillaume Viguier-Just
author_url = http://www.viguierjust.com
screenshots[] = screenshot.jpg
logo = logo.png
dependencies[apps_compatible] = apps_compatible 7.x-1.0-alpha2
dependencies[base_core] = base_core 7.x-1.0-alpha2
dependencies[base_media] = base_media 7.x-1.0-alpha1
dependencies[base_page] = base_page 7.x-1.0-alpha1
dependencies[features] = features 7.x-1.0
dependencies[media] = media 7.x-2.0-unstable6
dependencies[file_entity] = file_entity 7.x-2.0-unstable6
dependencies[ctools] = ctools 7.x-1.2
dependencies[pathauto] = pathauto 7.x-1.2
dependencies[roleassign] = roleassign 7.x-1.0-rc1
dependencies[role_export] = role_export 7.x-1.0
dependencies[token] = token 7.x-1.2
dependencies[strongarm] = strongarm 7.x-2.0
dependencies[title] = title 7.x-1.0-alpha4
downloadables[apps_compatible 7.x-1.0-alpha2] = http://ftp.drupal.org/files/projects/apps_compatible-7.x-1.0-alpha2.tar.gz
downloadables[base_core 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_core-7.x-1.0-alpha2.tar.gz
downloadables[base_media 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_media-7.x-1.0-alpha1.tar.gz
downloadables[base_page 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_page-7.x-1.0-alpha1.tar.gz
downloadables[features 7.x-1.0] = http://ftp.drupal.org/files/projects/features-7.x-1.0.tar.gz
downloadables[gvj_page 7.x-1.0-alpha1] = http://features.viguierjust.com/sites/features.viguierjust.com/files/fserver/gvj_page-7.x-1.0-alpha1.tgz
downloadables[media 7.x-2.0-unstable6] = http://ftp.drupal.org/files/projects/media-7.x-2.0-unstable6.tar.gz
downloadables[file_entity 7.x-2.0-unstable6] = http://ftp.drupal.org/files/projects/file_entity-7.x-2.0-unstable6.tar.gz
downloadables[ctools 7.x-1.2] = http://ftp.drupal.org/files/projects/ctools-7.x-1.2.tar.gz
downloadables[pathauto 7.x-1.2] = http://ftp.drupal.org/files/projects/pathauto-7.x-1.2.tar.gz
downloadables[roleassign 7.x-1.0-rc1] = http://ftp.drupal.org/files/projects/roleassign-7.x-1.0-rc1.tar.gz
downloadables[role_export 7.x-1.0] = http://ftp.drupal.org/files/projects/role_export-7.x-1.0.tar.gz
downloadables[token 7.x-1.2] = http://ftp.drupal.org/files/projects/token-7.x-1.2.tar.gz
downloadables[strongarm 7.x-2.0] = http://ftp.drupal.org/files/projects/strongarm-7.x-2.0.tar.gz
downloadables[title 7.x-1.0-alpha4] = http://ftp.drupal.org/files/projects/title-7.x-1.0-alpha4.tar.gz
