name = GVJ WYSIWYG
description = Enable WYSIWYG editor
machine_name = gvj_wysiwyg
version = 7.x-1.0-alpha1
downloadable = gvj_wysiwyg 7.x-1.0-alpha1
author = Guillaume Viguier-Just
author_url = http://www.viguierjust.com
screenshots[] = screenshot.png
logo = logo.png
dependencies[apps_compatible] = apps_compatible 7.x-1.0-alpha2
dependencies[base_core] = base_core 7.x-1.0-alpha2
dependencies[base_media] = base_media 7.x-1.0-alpha1
dependencies[base_wysiwyg] = base_wysiwyg 7.x-1.0-alpha1
dependencies[features] = features 7.x-1.0
dependencies[media] = media 7.x-2.0-unstable6
dependencies[file_entity] = file_entity 7.x-2.0-unstable6
dependencies[roleassign] = roleassign 7.x-1.0-rc1
dependencies[role_export] = role_export 7.x-1.0
dependencies[wysiwyg] = wysiwyg 7.x-2.2
downloadables[apps_compatible 7.x-1.0-alpha2] = http://ftp.drupal.org/files/projects/apps_compatible-7.x-1.0-alpha2.tar.gz
downloadables[base_core 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_core-7.x-1.0-alpha2.tar.gz
downloadables[base_media 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_media-7.x-1.0-alpha1.tar.gz
downloadables[base_wysiwyg 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_wysiwyg-7.x-1.0-alpha1.tar.gz
downloadables[features 7.x-1.0] = http://ftp.drupal.org/files/projects/features-7.x-1.0.tar.gz
downloadables[media 7.x-2.0-unstable6] = http://ftp.drupal.org/files/projects/media-7.x-2.0-unstable6.tar.gz
downloadables[file_entity 7.x-2.0-unstable6] = http://ftp.drupal.org/files/projects/file_entity-7.x-2.0-unstable6.tar.gz
downloadables[gvj_wysiwyg 7.x-1.0-alpha1] = http://features.viguierjust.com/sites/features.viguierjust.com/files/fserver/gvj_wysiwyg-7.x-1.0-alpha1.tgz
downloadables[roleassign 7.x-1.0-rc1] = http://ftp.drupal.org/files/projects/roleassign-7.x-1.0-rc1.tar.gz
downloadables[role_export 7.x-1.0] = http://ftp.drupal.org/files/projects/role_export-7.x-1.0.tar.gz
downloadables[wysiwyg 7.x-2.2] = http://ftp.drupal.org/files/projects/wysiwyg-7.x-2.2.tar.gz
