; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[apps_compatible][version] = 1.0-alpha2
projects[base_core][version] = 1.0-alpha1
projects[base_media][version] = 1.0-alpha1
projects[base_wysiwyg][version] = 1.0-alpha1
projects[features][version] = 1.0
projects[file_entity][version] = 2.0-unstable6
projects[media][version] = 2.0-unstable6
projects[roleassign][version] = 1.0-rc1
projects[role_export][version] = 1.0
projects[wysiwyg][version] = 2.2

; Libraries
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.3/ckeditor_3.6.3.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
