<?php

function sitedir_migrate_blocks_sitedir_query() {
  return 'Blocks';
}

function sitedir_migrate_blocks_sitedir_update($from, $to) {
  watchdog('Sitedir Migrate', 'Running the Block migration');
  db_query("UPDATE {block_custom} SET body = REPLACE(body, :old, :new)", array(':old' => $from, ':new' => $to));
  if (db_table_exists('locales_target') && db_table_exists('i18n_string')) {
    db_query("UPDATE {locales_target} SET translation = REPLACE(translation, :old, :new) WHERE lid IN (SELECT lid FROM {i18n_string} WHERE textgroup = :text)", array(':old' => $from, ':new' => $to, ':text' => 'blocks'));
  }
}
