; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[apps_compatible][version] = 1.0-alpha2
projects[base_core][version] = 1.0-alpha1
projects[base_media][version] = 1.0-alpha1
projects[base_page][version] = 1.0-alpha1
projects[features][version] = 1.0
projects[file_entity][version] = 2.0-unstable6
projects[media][version] = 2.0-unstable6
projects[pathauto][version] = 1.2
projects[roleassign][version] = 1.0-rc1
projects[role_export][version] = 1.0
projects[strongarm][version] = 2.0
projects[title][version] = 1.0-alpha4
projects[token][version] = 1.2
