<?php

function sitedir_migrate_body_sitedir_query() {
  return 'Node Bodies';
}

function sitedir_migrate_body_sitedir_update($from, $to) {
  watchdog('Sitedir Migrate', 'Running the Node Body migration');
  db_query("UPDATE {field_data_body} SET body_value = REPLACE(body_value,:old,:new)", array(':old' => $from, ':new' => $to));
  db_query("UPDATE {field_data_body} SET body_summary = REPLACE(body_summary,:old,:new)", array(':old' => $from, ':new' => $to));

  db_query("UPDATE {field_revision_body} SET body_value = REPLACE(body_value,:old,:new)", array(':old' => $from, ':new' => $to));
  db_query("UPDATE {field_revision_body} SET body_summary = REPLACE(body_summary,:old,:new)", array(':old' => $from, ':new' => $to));
}
