name = GVJ Social
description = Social media integration with sharethis and follow links.
machine_name = gvj_social
version = 7.x-1.0-alpha1
downloadable = gvj_social 7.x-1.0-alpha1
author = Guillaume Viguier-Just
author_url = http://www.viguierjust.com
screenshots[] = screenshot.png
logo = logo.png
dependencies[apps_compatible] = apps_compatible 7.x-1.0-alpha2
dependencies[base_core] = base_core 7.x-1.0-alpha2
dependencies[features] = features 7.x-1.0
dependencies[follow] = follow 7.x-1.0-alpha1
dependencies[roleassign] = roleassign 7.x-1.0-rc1
dependencies[role_export] = role_export 7.x-1.0
dependencies[sharethis] = sharethis 7.x-2.4
downloadables[apps_compatible 7.x-1.0-alpha2] = http://ftp.drupal.org/files/projects/apps_compatible-7.x-1.0-alpha2.tar.gz
downloadables[base_core 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_core-7.x-1.0-alpha2.tar.gz
downloadables[features 7.x-1.0] = http://ftp.drupal.org/files/projects/features-7.x-1.0.tar.gz
downloadables[follow 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/follow-7.x-1.0-alpha1.tar.gz
downloadables[gvj_social 7.x-1.0-alpha1] = http://features.viguierjust.com/sites/features.viguierjust.com/files/fserver/gvj_social-7.x-1.0-alpha1.tgz
downloadables[roleassign 7.x-1.0-rc1] = http://ftp.drupal.org/files/projects/roleassign-7.x-1.0-rc1.tar.gz
downloadables[role_export 7.x-1.0] = http://ftp.drupal.org/files/projects/role_export-7.x-1.0.tar.gz
downloadables[sharethis 7.x-2.4] = http://ftp.drupal.org/files/projects/sharethis-7.x-2.4.tar.gz
