name = GVJ Webform
description = Create forms on your site.
machine_name = gvj_webform
version = 7.x-1.0-alpha1
downloadable = gvj_webform 7.x-1.0-alpha1
author = Guillaume Viguier-Just
author_url = http://www.viguierjust.com
screenshots[] = screenshot.png
logo = logo.png
dependencies[apps_compatible] = apps_compatible 7.x-1.0-alpha2
dependencies[base_core] = base_core 7.x-1.0-alpha2
dependencies[features] = features 7.x-1.0
dependencies[roleassign] = roleassign 7.x-1.0-rc1
dependencies[role_export] = role_export 7.x-1.0
dependencies[webform] = webform 7.x-3.18
downloadables[apps_compatible 7.x-1.0-alpha2] = http://ftp.drupal.org/files/projects/apps_compatible-7.x-1.0-alpha2.tar.gz
downloadables[base_core 7.x-1.0-alpha1] = http://ftp.drupal.org/files/projects/base_core-7.x-1.0-alpha2.tar.gz
downloadables[features 7.x-1.0] = http://ftp.drupal.org/files/projects/features-7.x-1.0.tar.gz
downloadables[gvj_webform 7.x-1.0-alpha1] = http://features.viguierjust.com/sites/features.viguierjust.com/files/fserver/gvj_webform-7.x-1.0-alpha1.tgz
downloadables[roleassign 7.x-1.0-rc1] = http://ftp.drupal.org/files/projects/roleassign-7.x-1.0-rc1.tar.gz
downloadables[role_export 7.x-1.0] = http://ftp.drupal.org/files/projects/role_export-7.x-1.0.tar.gz
downloadables[webform 7.x-3.18] = http://ftp.drupal.org/files/projects/webform-7.x-3.18.tar.gz
